blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/juanmanueldaza/futureproof/discussions/new?category=q-a
    about: Ask and answer questions here.
  - name: Propose a new feature
    url: https://github.com/juanmanueldaza/futureproof/discussions/new?category=ideas
    about: "Got an idea? Let's discuss it!"
  - name: Report a security vulnerability
    url: https://github.com/juanmanueldaza/futureproof/security/policy
    about: Please review our security policy for reporting vulnerabilities.
